[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "bluetooth-sniffer"
version = "0.1.0"
description = "A portable BLE analysis and testing tool"
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
authors = [
    { name = "Anton Igudesman" }
]
dependencies = [
    "bleak==3.0.2"
]

[project.scripts]
bluetooth-sniffer = "bluetooth_sniffer.cli:run"
bluetooth-sniffer-analyze = "bluetooth_sniffer.analysis_cli:run"
bluetooth-sniffer-display = "bluetooth_sniffer.display.app:run"